server:
  port: 8081
  servlet:
    context-path: /file-upload

output:
  file:
    path: C:/output/uploads/

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB